router:
  name: gin
  options:
    key: val
    key2: val2

services:
  - name: service-a
    loadbalancer: round-robin
    backends:
      - name: a
        weight: 1
        address: https://google.com

rules:
  - service: service-a
    schema: https
    path-prefix: /pre
    hosts:
      - www.foo.bar
    methods:
      - GET
      - POST
    headers:
      key:
        - val1
        - val2
      key2:
        - val11
        - val12
    queries:
      key: val
      key2: val2
    middlewares:
      - middleware-1
      - middleware-2

middlewares:
  - name: custom-1
    plugin-path: /path/to/file.so
    params:
      key: val
      key1: val
  - name: middleware-2
    params:
      key: val
      key1: val